name: ribo
dependencies:
    # python reqs
    - python=3.5
    - biopython=1.68
    - jenkspy=0.1.4
    - pyaml=17.8.0
    - pysam=0.11.2.2
    - pyutilsnrw=0.1.1
    - matplotlib=1.5.3
    - pandas=0.20.1
    - coverage=4.4.1
    - nose=1.3.7
    # sys reqs
    - emboss
    - barrnap ==0.7
    - mafft
    - prank
    - spades ==3.9.0
    - bwa ==0.7.8
    - samtools ==1.4.1
    - bcftools ==1.5
    - quast
    - bedtools
