# Generated by riboSelect.py on Tue Oct  4 00:10:24 2016
centers <- 3
data <- read.csv('list.csv', header=F, col.names=c('index'))
set.seed(27)
km <- kmeans(data[,1], nstart=100,iter.max=100,centers=centers)
data[,2] <- km[1]
data <- data[order(data[,1]),  ]
write.table(data, 'list.csv', sep=',', row.names=F, col.names=F)
