# Generated by riboSelect.py on Thu Sep 29 00:46:59 2016
centers <- 6
data <- read.csv('list.csv', header=F, col.names=c('index'))
km <- kmeans(data[,1], nstart=100,iter.max=100,centers=centers)
data[,2] <- km[1]
data <- data[order(data[,1]),  ]
write.csv(data, 'list.csv',  row.names=F)
