# Generated by riboSnag.py on Fri Oct 28 11:10:48 2016
data <- read.csv('/home/nicholas/GitHub/riboSeed/tests/output_riboSnag_tests/test_generated_entropy_plot.csv', stringsAsFactors = F)
pdf(file='/home/nicholas/GitHub/riboSeed/tests/output_riboSnag_tests/test_generated_entropy_plot.pdf', width=6, height=4)
plot(data, cex=.75, pch=18, axes=FALSE, xaxs='i', yaxs='i', ylim=c(-0.1, 2), xlab='', ylab='')
mtext('Sample', side=3, line=0.5, cex.lab=1,las=1, col='#34282C')
axis(2, col='darkgrey')
axis(1, col='darkgrey')
title('Shannon Entropy', xlab='Position (bp)', ylab='Entropy')
dev.off()
